@host=http://localhost
@port=5003

### INGREDIENTS

### Sugar (with image + description)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Sugar",
  "Description": "fine white sugar commonly used as a sweetener",
  "ImageUrl": "https://images.unsplash.com/photo-1709651808265-977ed7ef78c6?q=80&w=1738&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing1", response.body); %}

### Mint (with description only)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Mint",
  "Description": "fresh aromatic green leaves"
}
> {% client.global.set("ing2", response.body); %}

### Lime (with image only)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Lime",
  "ImageUrl": "https://images.unsplash.com/photo-1648437595604-f1794490053c?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing3", response.body); %}

### Lemon (full)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Lemon",
  "Description": "sour yellow citrus fruit",
  "ImageUrl": "https://i.imgur.com/YYPzexp.png"
}
> {% client.global.set("ing4", response.body); %}

### Soda (minimal)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Soda"
}
> {% client.global.set("ing5", response.body); %}

### Rum (with description)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Rum",
  "Description": "distilled alcoholic beverage from sugarcane"
}
> {% client.global.set("ing6", response.body); %}

### Vodka (with image)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Vodka",
  "ImageUrl": "https://images.unsplash.com/photo-1595430712287-744ad635e266?q=80&w=1354&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing7", response.body); %}

### Orange Juice (full)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Orange Juice",
  "Description": "freshly squeezed orange juice",
  "ImageUrl": "https://images.unsplash.com/photo-1613478223719-2ab802602423?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing8", response.body); %}

### Ice (minimal)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Ice"
}
> {% client.global.set("ing9", response.body); %}

### Coffee (with description)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Coffee",
  "Description": "strong brewed black coffee"
}
> {% client.global.set("ing10", response.body); %}

### Milk (with image)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Milk",
  "ImageUrl": "https://images.unsplash.com/photo-1550583724-b2692b85b150?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing11", response.body); %}

### Chocolate (full)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Chocolate",
  "Description": "sweet cocoa-based ingredient",
  "ImageUrl": "https://images.unsplash.com/photo-1626697556651-67ebdcb8cbd6?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing12", response.body); %}

### Banana (description only)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Banana",
  "Description": "soft tropical fruit"
}
> {% client.global.set("ing13", response.body); %}

### Strawberry (image only)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Strawberry",
  "ImageUrl": "https://images.unsplash.com/photo-1722803672529-5a7a85728479?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing14", response.body); %}

### Water (minimal)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Water"
}
> {% client.global.set("ing15", response.body); %}



### RECIPES
### Create Mojito (full)
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Mojito",
  "description": "fresh mint cocktail",
  "imageUrl": "https://images.unsplash.com/photo-1659046842567-2787b5c9c2fe?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "duration": "00:05:00",
  "type": 1
}
> {% client.global.set("rec1", response.body); %}


### Create Lemonade (no image)
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Lemonade",
  "description": "simple refreshing drink",
  "duration": "00:03:00",
  "type": 0
}
> {% client.global.set("rec2", response.body); %}


### Create Orange Drink (minimal)
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Orange Drink",
  "duration": "00:02:00",
  "type": 0
}
> {% client.global.set("rec3", response.body); %}


### Create Latte (with description only)
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Latte",
  "description": "coffee with steamed milk",
  "duration": "00:04:00",
  "type": 3
}
> {% client.global.set("rec4", response.body); %}


### Create Chocolate Milkshake (full)
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Chocolate Milkshake",
  "description": "sweet cold dessert drink",
  "imageUrl": "https://images.unsplash.com/photo-1571328003758-4a3921661729?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "duration": "00:06:00",
  "type": 2
}
> {% client.global.set("rec5", response.body); %}


### Create Strawberry Smoothie (image only)
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Strawberry Smoothie",
  "imageUrl": "https://images.unsplash.com/photo-1553530666-ba11a7da3888?q=80&w=686&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "duration": "00:05:00",
  "type": 4
}
> {% client.global.set("rec6", response.body); %}





### Mojito Ingredients
POST {{host}}:{{port}}/recipe/{{rec1}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing3}}", "amount": 1, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec1}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing2}}", "amount": 5, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec1}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing1}}", "amount": 10, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec1}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing6}}", "amount": 50, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec1}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing5}}", "amount": 200, "unit": 1 }




### Lemonade Ingredients
POST {{host}}:{{port}}/recipe/{{rec2}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing4}}", "amount": 2, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec2}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing1}}", "amount": 20, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec2}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing15}}", "amount": 500, "unit": 1 }



### Orange Drink Ingredients
POST {{host}}:{{port}}/recipe/{{rec3}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing8}}", "amount": 250, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec3}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing9}}", "amount": 5, "unit": 0 }



### Latte Ingredients
POST {{host}}:{{port}}/recipe/{{rec4}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing10}}", "amount": 200, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec4}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing11}}", "amount": 100, "unit": 1 }



### Milkshake Ingredients
POST {{host}}:{{port}}/recipe/{{rec5}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing11}}", "amount": 300, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec5}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing12}}", "amount": 50, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec5}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing13}}", "amount": 1, "unit": 0 }



### Smoothie Ingredients
POST {{host}}:{{port}}/recipe/{{rec6}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing14}}", "amount": 5, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec6}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing11}}", "amount": 200, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec6}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing1}}", "amount": 10, "unit": 3 }
