@host=http://localhost
@port=5003

### INGREDIENTS

### Sugar (with image + description)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Sugar",
  "Description": "fine white sugar commonly used as a sweetener",
  "ImageUrl": "https://images.unsplash.com/photo-1709651808265-977ed7ef78c6?q=80&w=1738&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing1", response.body); %}

### Mint (with description only)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Mint",
  "Description": "fresh aromatic green leaves"
}
> {% client.global.set("ing2", response.body); %}

### Lime (with image only)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Lime",
  "ImageUrl": "https://images.unsplash.com/photo-1648437595604-f1794490053c?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing3", response.body); %}

### Lemon (full)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Lemon",
  "Description": "sour yellow citrus fruit",
  "ImageUrl": "https://i.imgur.com/YYPzexp.png"
}
> {% client.global.set("ing4", response.body); %}

### Soda (minimal)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Soda"
}
> {% client.global.set("ing5", response.body); %}

### Rum (with description)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Rum",
  "Description": "distilled alcoholic beverage from sugarcane"
}
> {% client.global.set("ing6", response.body); %}

### Vodka (with image)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Vodka",
  "ImageUrl": "https://images.unsplash.com/photo-1595430712287-744ad635e266?q=80&w=1354&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing7", response.body); %}

### Orange Juice (full)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Orange Juice",
  "Description": "freshly squeezed orange juice",
  "ImageUrl": "https://images.unsplash.com/photo-1613478223719-2ab802602423?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing8", response.body); %}

### Ice (minimal)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Ice"
}
> {% client.global.set("ing9", response.body); %}

### Coffee (with description)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Coffee",
  "Description": "strong brewed black coffee"
}
> {% client.global.set("ing10", response.body); %}

### Milk (with image)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Milk",
  "ImageUrl": "https://images.unsplash.com/photo-1550583724-b2692b85b150?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing11", response.body); %}

### Chocolate (full)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Chocolate",
  "Description": "sweet cocoa-based ingredient",
  "ImageUrl": "https://images.unsplash.com/photo-1626697556651-67ebdcb8cbd6?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing12", response.body); %}

### Banana (description only)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Banana",
  "Description": "soft tropical fruit"
}
> {% client.global.set("ing13", response.body); %}

### Strawberry (image only)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Strawberry",
  "ImageUrl": "https://images.unsplash.com/photo-1722803672529-5a7a85728479?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing14", response.body); %}

### Water (minimal)
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Water"
}
> {% client.global.set("ing15", response.body); %}

### Vanilla Syrup
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Vanilla Syrup",
  "Description": "sweet vanilla flavored syrup",
  "ImageUrl": "https://images.unsplash.com/photo-1770376924086-5c9f36723081?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing16", response.body); %}

### Caramel Syrup
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Caramel Syrup",
  "Description": "rich caramel coffee syrup",
  "ImageUrl": "https://plus.unsplash.com/premium_photo-1695397417667-f731fc33c206?q=80&w=688&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing17", response.body); %}

### Cinnamon
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Cinnamon",
  "ImageUrl": "https://images.unsplash.com/photo-1553499944-e4297a0af1bd?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
  
}
> {% client.global.set("ing18", response.body); %}

### Honey
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Honey",
  "ImageUrl": "https://images.unsplash.com/photo-1613548058193-1cd24c1bebcf?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
  
}
> {% client.global.set("ing19", response.body); %}

### Green Tea
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Green Tea",
  "Description": "ground green tea or brewed concentrate",
  "ImageUrl": "https://images.unsplash.com/photo-1546662661-de70c19756be?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing20", response.body); %}

### Black Tea
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Black Tea",
  "ImageUrl": "https://images.unsplash.com/photo-1627828094454-accc9a7c20e9?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing21", response.body); %}

### Ginger
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Ginger",
  "Description": "fresh aromatic ginger root",
  "ImageUrl": "https://images.unsplash.com/photo-1635843104103-ddd88e1c5141?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing22", response.body); %}

### Apple Juice
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Apple Juice",
  "ImageUrl": "https://images.unsplash.com/photo-1590240568206-4e97becae4ef?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing23", response.body); %}

### Pineapple Juice
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Pineapple Juice",
  "ImageUrl": "https://images.unsplash.com/photo-1636386794950-aae736311f41?q=80&w=1163&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing24", response.body); %}

### Cranberry Juice
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Cranberry Juice",
  "ImageUrl": "https://plus.unsplash.com/premium_photo-1671405507937-3c335f3aef11?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing25", response.body); %}

### Tonic Water
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Tonic Water",
  "ImageUrl": "https://images.unsplash.com/photo-1652256071713-ffc3d9f6bdf3?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing26", response.body); %}

### Gin
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Gin",
  "ImageUrl": "https://images.unsplash.com/photo-1700485869901-d22cf64c4d7d?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing27", response.body); %}

### Tequila
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Tequila",
  "ImageUrl": "https://images.unsplash.com/photo-1529671434436-8fbb37410056?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing28", response.body); %}

### Triple Sec
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Triple Sec",
  "ImageUrl": "https://images.unsplash.com/photo-1774537642349-f84ae0f4e2f8?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}
> {% client.global.set("ing29", response.body); %}

### Whiskey
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Whiskey"
}
> {% client.global.set("ing30", response.body); %}

### Red Wine
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Red Wine"
}
> {% client.global.set("ing31", response.body); %}

### Beer
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Beer"
}
> {% client.global.set("ing32", response.body); %}

### Butter
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Butter"
}
> {% client.global.set("ing33", response.body); %}

### Flour
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Flour"
}
> {% client.global.set("ing34", response.body); %}

### Egg
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Egg"
}
> {% client.global.set("ing35", response.body); %}

### Baking Powder
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Baking Powder"
}
> {% client.global.set("ing36", response.body); %}

### Vanilla Extract
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Vanilla Extract"
}
> {% client.global.set("ing37", response.body); %}

### Cream Cheese
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Cream Cheese"
}
> {% client.global.set("ing38", response.body); %}

### Mascarpone
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Mascarpone"
}
> {% client.global.set("ing39", response.body); %}

### Ladyfingers
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Ladyfingers"
}
> {% client.global.set("ing40", response.body); %}

### Espresso Shot
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Espresso Shot"
}
> {% client.global.set("ing41", response.body); %}

### Cocoa Powder
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Cocoa Powder"
}
> {% client.global.set("ing42", response.body); %}

### Whipped Cream
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Whipped Cream"
}
> {% client.global.set("ing43", response.body); %}

### Oats
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Oats"
}
> {% client.global.set("ing44", response.body); %}

### Yogurt
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Yogurt"
}
> {% client.global.set("ing45", response.body); %}

### Blueberries
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Blueberries"
}
> {% client.global.set("ing46", response.body); %}

### Raspberries
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Raspberries"
}
> {% client.global.set("ing47", response.body); %}

### Coconut Milk
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Coconut Milk"
}
> {% client.global.set("ing48", response.body); %}

### Orange Liqueur
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Orange Liqueur"
}
> {% client.global.set("ing49", response.body); %}

### Soda Water
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Soda Water"
}
> {% client.global.set("ing50", response.body); %}

### Tatratea 22%
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Tatratea 22%",
  "ImageUrl": "https://tatrateashop.sk/wp-content/uploads/2024/05/tatratea_22_coconut.png"
}
> {% client.global.set("ing51", response.body); %}

### Tatratea 32%
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Tatratea 32%",
  "ImageUrl": "https://tatrateashop.sk/wp-content/uploads/2024/05/tatratea_32_citrus.png"
}
> {% client.global.set("ing52", response.body); %}
### Tatratea 42%
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Tatratea 42%",
  "ImageUrl": "https://tatrateashop.sk/wp-content/uploads/2024/05/tatratea_42_peach.png"
}
> {% client.global.set("ing53", response.body); %}

### Tatratea 52%
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Tatratea 52%",
  "ImageUrl": "https://tatrateashop.sk/wp-content/uploads/2024/05/tatratea_52_original.png"
}
> {% client.global.set("ing54", response.body); %}

### Tatratea 62%
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Tatratea 62%",
  "ImageUrl": "https://tatrateashop.sk/wp-content/uploads/2024/05/tatratea_62_forest_fruit.png"
}
> {% client.global.set("ing55", response.body); %}

### Tatratea 72%
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Tatratea 72%",
  "ImageUrl": "https://tatrateashop.sk/wp-content/uploads/2024/05/tatratea_72_outlaw.png"
}
> {% client.global.set("ing56", response.body); %}


### RECIPES
### Create Mojito (full)
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Mojito",
  "description": "fresh mint cocktail",
  "imageUrl": "https://images.unsplash.com/photo-1659046842567-2787b5c9c2fe?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "duration": "00:05:00",
  "type": 1
}
> {% client.global.set("rec1", response.body); %}


### Create Lemonade (no image)
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Lemonade",
  "description": "simple refreshing drink",
  "duration": "00:03:00",
  "type": 0
}
> {% client.global.set("rec2", response.body); %}


### Create Orange Drink (minimal)
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Orange Drink",
  "duration": "00:02:00",
  "type": 0
}
> {% client.global.set("rec3", response.body); %}


### Create Latte (with description only)
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Latte",
  "description": "coffee with steamed milk",
  "duration": "00:04:00",
  "type": 3
}
> {% client.global.set("rec4", response.body); %}


### Create Chocolate Milkshake (full)
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Chocolate Milkshake",
  "description": "sweet cold dessert drink",
  "imageUrl": "https://images.unsplash.com/photo-1571328003758-4a3921661729?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "duration": "00:06:00",
  "type": 2
}
> {% client.global.set("rec5", response.body); %}


### Create Strawberry Smoothie (image only)
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Strawberry Smoothie",
  "imageUrl": "https://images.unsplash.com/photo-1553530666-ba11a7da3888?q=80&w=686&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "duration": "00:05:00",
  "type": 4
}
> {% client.global.set("rec6", response.body); %}


### Create Cappuccino
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Cappuccino",
  "description": "espresso coffee with milk foam",
  "duration": "00:04:00",
  "imageUrl": "https://images.unsplash.com/photo-1594261956806-3ad03785c9b4?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 3
}
> {% client.global.set("rec7", response.body); %}

### Create Caramel Macchiato
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Caramel Macchiato",
  "description": "espresso with milk and caramel",
  "duration": "00:05:00",
  "imageUrl": "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 3
}
> {% client.global.set("rec8", response.body); %}

### Create Iced Americano
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Iced Americano",
  "description": "cold espresso diluted with water",
  "duration": "00:03:00",
  "imageUrl": "https://images.unsplash.com/photo-1627898784518-b6ee18b7f22a?q=80&w=1026&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 3
}
> {% client.global.set("rec9", response.body); %}

### Create Matcha Latte
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Matcha Latte",
  "description": "creamy green tea latte",
  "duration": "00:04:00",
  "imageUrl": "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 3
}
> {% client.global.set("rec10", response.body); %}

### Create Chai Latte
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Chai Latte",
  "description": "spiced black tea with milk",
  "duration": "00:05:00",
  "imageUrl": "https://images.unsplash.com/photo-1561336526-2914f13ceb36?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 3
}
> {% client.global.set("rec11", response.body); %}

### Create Gin Tonic
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Gin Tonic",
  "description": "classic gin and tonic cocktail",
  "duration": "00:03:00",
  "imageUrl": "https://images.unsplash.com/photo-1675370734208-120b43d3c7ac?q=80&w=686&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 1
}
> {% client.global.set("rec12", response.body); %}

### Create Margarita
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Margarita",
  "description": "tequila citrus cocktail",
  "duration": "00:04:00",
  "imageUrl": "https://images.unsplash.com/photo-1655546837806-76a6dd54ee2b?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 1
}
> {% client.global.set("rec13", response.body); %}

### Create Cosmopolitan
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Cosmopolitan",
  "description": "vodka cocktail with cranberry and citrus",
  "duration": "00:04:00",
  "imageUrl": "https://images.unsplash.com/photo-1556855810-ac404aa91e85?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 1
}
> {% client.global.set("rec14", response.body); %}

### Create Whiskey Sour
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Whiskey Sour",
  "description": "balanced sour whiskey cocktail",
  "duration": "00:04:00",
  "imageUrl": "https://images.unsplash.com/photo-1713720441159-466472b29b54?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 1
}
> {% client.global.set("rec15", response.body); %}

### Create Pina Colada
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Pina Colada",
  "description": "tropical rum and coconut cocktail",
  "duration": "00:05:00",
  "imageUrl": "https://images.unsplash.com/photo-1607644536940-6c300b5784c5?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 1
}
> {% client.global.set("rec16", response.body); %}

### Create Virgin Pina Colada
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Virgin Pina Colada",
  "description": "nonalcoholic pineapple coconut drink",
  "imageUrl": "https://images.unsplash.com/photo-1607644536940-6c300b5784c5?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "duration": "00:05:00",
  "type": 0
}
> {% client.global.set("rec17", response.body); %}

### Create Lemon Iced Tea
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Lemon Iced Tea",
  "description": "chilled black tea with lemon",
  "imageUrl": "https://images.unsplash.com/photo-1599390719613-912787a6e65a?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "duration": "00:04:00",
  "type": 0
}
> {% client.global.set("rec18", response.body); %}

### Create Berry Smoothie
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Berry Smoothie",
  "description": "mixed berry yogurt smoothie",
  "duration": "00:05:00",
  "imageUrl": "https://images.unsplash.com/photo-1643470758221-45463a3d210a?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 4
}
> {% client.global.set("rec19", response.body); %}

### Create Cheesecake Cup
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Cheesecake Cup",
  "description": "no-bake cream cheese dessert cup",
  "duration": "00:12:00",
  "imageUrl": "https://images.unsplash.com/photo-1561804558-fcfafc5a963e?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 2
}
> {% client.global.set("rec20", response.body); %}

### Create Tiramisu Cup
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Tiramisu Cup",
  "description": "coffee layered mascarpone dessert",
  "duration": "00:15:00",
  "imageUrl": "https://images.unsplash.com/photo-1766232333746-b0a2697d6d0d?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 2
}
> {% client.global.set("rec21", response.body); %}

### Create Pancake Batter
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Pancake Batter",
  "description": "classic sweet pancake base",
  "duration": "00:08:00",
  "imageUrl": "https://images.unsplash.com/photo-1583611177793-a31c8df1d67f?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 2
}
> {% client.global.set("rec22", response.body); %}

### Create Banana Oat Shake
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Banana Oat Shake",
  "description": "filling breakfast-style shake",
  "duration": "00:04:00",
  "imageUrl": "https://images.unsplash.com/photo-1740637372899-e27569049917?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 4
}
> {% client.global.set("rec23", response.body); %}

### Create Chocolate Cake Batter
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Chocolate Cake Batter",
  "description": "rich cocoa cake preparation",
  "duration": "00:12:00",
  "imageUrl": "https://images.unsplash.com/photo-1607662256021-751dc3939f2b?q=80&w=1174&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 2
}
> {% client.global.set("rec24", response.body); %}

### Create Honey Ginger Tea
POST {{host}}:{{port}}/recipe
Content-Type: application/json

{
  "name": "Honey Ginger Tea",
  "description": "warming tea with ginger and honey",
  "duration": "00:04:00",
  "imageUrl": "https://images.unsplash.com/photo-1606695889004-f7850b9bfb81?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "type": 0
}
> {% client.global.set("rec25", response.body); %}


### Mojito Ingredients
POST {{host}}:{{port}}/recipe/{{rec1}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing3}}", "amount": 1, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec1}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing2}}", "amount": 5, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec1}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing1}}", "amount": 10, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec1}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing6}}", "amount": 50, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec1}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing5}}", "amount": 200, "unit": 1 }



### Lemonade Ingredients
POST {{host}}:{{port}}/recipe/{{rec2}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing4}}", "amount": 2, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec2}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing1}}", "amount": 20, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec2}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing15}}", "amount": 500, "unit": 1 }



### Orange Drink Ingredients
POST {{host}}:{{port}}/recipe/{{rec3}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing8}}", "amount": 250, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec3}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing9}}", "amount": 5, "unit": 0 }



### Latte Ingredients
POST {{host}}:{{port}}/recipe/{{rec4}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing10}}", "amount": 200, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec4}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing11}}", "amount": 100, "unit": 1 }



### Milkshake Ingredients
POST {{host}}:{{port}}/recipe/{{rec5}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing11}}", "amount": 300, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec5}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing12}}", "amount": 50, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec5}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing13}}", "amount": 1, "unit": 0 }



### Smoothie Ingredients
POST {{host}}:{{port}}/recipe/{{rec6}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing14}}", "amount": 5, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec6}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing11}}", "amount": 200, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec6}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing1}}", "amount": 10, "unit": 3 }



### Cappuccino Ingredients
POST {{host}}:{{port}}/recipe/{{rec7}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing41}}", "amount": 2, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec7}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing11}}", "amount": 150, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec7}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing1}}", "amount": 8, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec7}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing18}}", "amount": 1, "unit": 3 }

### Caramel Macchiato Ingredients
POST {{host}}:{{port}}/recipe/{{rec8}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing41}}", "amount": 2, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec8}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing11}}", "amount": 180, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec8}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing17}}", "amount": 20, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec8}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing16}}", "amount": 10, "unit": 1 }

### Iced Americano Ingredients
POST {{host}}:{{port}}/recipe/{{rec9}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing41}}", "amount": 2, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec9}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing15}}", "amount": 200, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec9}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing9}}", "amount": 6, "unit": 0 }

### Matcha Latte Ingredients
POST {{host}}:{{port}}/recipe/{{rec10}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing20}}", "amount": 6, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec10}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing11}}", "amount": 220, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec10}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing1}}", "amount": 10, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec10}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing16}}", "amount": 10, "unit": 1 }

### Chai Latte Ingredients
POST {{host}}:{{port}}/recipe/{{rec11}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing21}}", "amount": 180, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec11}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing11}}", "amount": 150, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec11}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing19}}", "amount": 12, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec11}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing18}}", "amount": 2, "unit": 3 }

### Gin Tonic Ingredients
POST {{host}}:{{port}}/recipe/{{rec12}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing27}}", "amount": 50, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec12}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing26}}", "amount": 150, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec12}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing3}}", "amount": 1, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec12}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing9}}", "amount": 5, "unit": 0 }

### Margarita Ingredients
POST {{host}}:{{port}}/recipe/{{rec13}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing28}}", "amount": 50, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec13}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing29}}", "amount": 20, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec13}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing4}}", "amount": 1, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec13}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing1}}", "amount": 5, "unit": 3 }

### Cosmopolitan Ingredients
POST {{host}}:{{port}}/recipe/{{rec14}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing7}}", "amount": 40, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec14}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing25}}", "amount": 40, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec14}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing49}}", "amount": 15, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec14}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing4}}", "amount": 1, "unit": 0 }

### Whiskey Sour Ingredients
POST {{host}}:{{port}}/recipe/{{rec15}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing30}}", "amount": 50, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec15}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing4}}", "amount": 1, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec15}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing1}}", "amount": 12, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec15}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing9}}", "amount": 4, "unit": 0 }

### Pina Colada Ingredients
POST {{host}}:{{port}}/recipe/{{rec16}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing6}}", "amount": 50, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec16}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing24}}", "amount": 120, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec16}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing48}}", "amount": 100, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec16}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing9}}", "amount": 6, "unit": 0 }

### Virgin Pina Colada Ingredients
POST {{host}}:{{port}}/recipe/{{rec17}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing24}}", "amount": 150, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec17}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing48}}", "amount": 120, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec17}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing19}}", "amount": 10, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec17}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing9}}", "amount": 6, "unit": 0 }

### Lemon Iced Tea Ingredients
POST {{host}}:{{port}}/recipe/{{rec18}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing21}}", "amount": 250, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec18}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing4}}", "amount": 1, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec18}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing1}}", "amount": 12, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec18}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing9}}", "amount": 5, "unit": 0 }

### Berry Smoothie Ingredients
POST {{host}}:{{port}}/recipe/{{rec19}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing14}}", "amount": 4, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec19}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing46}}", "amount": 40, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec19}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing47}}", "amount": 40, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec19}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing45}}", "amount": 180, "unit": 1 }

### Cheesecake Cup Ingredients
POST {{host}}:{{port}}/recipe/{{rec20}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing38}}", "amount": 200, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec20}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing11}}", "amount": 80, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec20}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing1}}", "amount": 35, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec20}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing37}}", "amount": 5, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec20}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing43}}", "amount": 40, "unit": 1 }

### Tiramisu Cup Ingredients
POST {{host}}:{{port}}/recipe/{{rec21}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing39}}", "amount": 200, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec21}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing40}}", "amount": 8, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec21}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing41}}", "amount": 2, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec21}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing42}}", "amount": 10, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec21}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing1}}", "amount": 30, "unit": 3 }

### Pancake Batter Ingredients
POST {{host}}:{{port}}/recipe/{{rec22}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing34}}", "amount": 200, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec22}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing11}}", "amount": 250, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec22}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing35}}", "amount": 2, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec22}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing33}}", "amount": 40, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec22}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing36}}", "amount": 8, "unit": 3 }

### Banana Oat Shake Ingredients
POST {{host}}:{{port}}/recipe/{{rec23}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing13}}", "amount": 1, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec23}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing44}}", "amount": 40, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec23}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing11}}", "amount": 250, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec23}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing19}}", "amount": 8, "unit": 3 }

### Chocolate Cake Batter Ingredients
POST {{host}}:{{port}}/recipe/{{rec24}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing34}}", "amount": 220, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec24}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing42}}", "amount": 45, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec24}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing35}}", "amount": 3, "unit": 0 }

###
POST {{host}}:{{port}}/recipe/{{rec24}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing33}}", "amount": 90, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec24}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing1}}", "amount": 160, "unit": 3 }

### Honey Ginger Tea Ingredients
POST {{host}}:{{port}}/recipe/{{rec25}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing22}}", "amount": 15, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec25}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing19}}", "amount": 12, "unit": 3 }

###
POST {{host}}:{{port}}/recipe/{{rec25}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing15}}", "amount": 250, "unit": 1 }

###
POST {{host}}:{{port}}/recipe/{{rec25}}/ingredient
Content-Type: application/json

{ "ingredientId": "{{ing4}}", "amount": 1, "unit": 0 }
