@host=http://localhost
@port=5003

###
# Gets list of ingredients (initial)
GET {{host}}:{{port}}/ingredient
Accept: application/json

### Create first ingredient
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Test ingredient",
  "Descripton": "test description",
  "ImageUrl": ""
}
> {% client.global.set("ingredient1id", response.body); %}

### Create second ingredient
POST {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Name": "Test second ingredient",
  "Descripton": "one more ingredient",
  "ImageUrl": "some image url"
}
> {% client.global.set("ingredient2id", response.body); %}

###
# Gets list of ingredients (after adds)
GET {{host}}:{{port}}/ingredient
Accept: application/json

###
# Gets second ingredient by id (uses response variable)
GET {{host}}:{{port}}/ingredient/{{ingredient2id}}
Accept: application/json

###
# Update the second ingredient
PUT {{host}}:{{port}}/ingredient
Content-Type: application/json

{
  "Id": "{{ingredient2id}}",
  "Name": "Updated name123",
  "Descripton": "updated description",
  "ImageUrl": "some deffierent image url"
}

###
# Gets second ingredient by id (after update)
GET {{host}}:{{port}}/ingredient/{{ingredient2id}}
Accept: application/json

###
# Deletes second ingredient
DELETE {{host}}:{{port}}/ingredient/{{ingredient2id}}

###
# Gets deleted second ingredient (should be 404)
GET {{host}}:{{port}}/ingredient/{{ingredient2id}}
Accept: application/json

###
# Gets list of ingredients and second should no longer be there
GET {{host}}:{{port}}/ingredient
Accept: application/json
