//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookBook.CleanArch.Presentation.MauiApplication.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DomainErrorTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainErrorTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CookBook.CleanArch.Presentation.MauiApplication.Resources.Texts.DomainErrorTexts", typeof(DomainErrorTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient {0} not found.
        /// </summary>
        internal static string Ingredients_IngredientNotFound {
            get {
                return ResourceManager.GetString("Ingredients.IngredientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete ingredient that is used in {0} recipes. Remove it from all recipes first..
        /// </summary>
        internal static string Ingredients_InUseCannotDelete {
            get {
                return ResourceManager.GetString("Ingredients.InUseCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient name can not be empty..
        /// </summary>
        internal static string Ingredients_NameEmpty {
            get {
                return ResourceManager.GetString("Ingredients.NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ingredient must be selected..
        /// </summary>
        internal static string RecipeIngredient_IngredientMustBeSelected {
            get {
                return ResourceManager.GetString("RecipeIngredient.IngredientMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit must be selected..
        /// </summary>
        internal static string RecipeIngredient_UnitMustBeSelected {
            get {
                return ResourceManager.GetString("RecipeIngredient.UnitMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe can not have more than 10 ingredients..
        /// </summary>
        internal static string Recipes_MaximumNumberOfIngredientsExceeded {
            get {
                return ResourceManager.GetString("Recipes.MaximumNumberOfIngredientsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe {0} can not have more than 10 ingredients..
        /// </summary>
        internal static string Recipes_MaximumNumberOfIngredientsExceeded_ForRecipe {
            get {
                return ResourceManager.GetString("Recipes.MaximumNumberOfIngredientsExceeded.ForRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe must contain at least 1 ingredient..
        /// </summary>
        internal static string Recipes_MinimumNumberOfIngredientsRequired {
            get {
                return ResourceManager.GetString("Recipes.MinimumNumberOfIngredientsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe {0} must contain at least 1 ingredient..
        /// </summary>
        internal static string Recipes_MinimumNumberOfIngredientsRequired_ForRecipe {
            get {
                return ResourceManager.GetString("Recipes.MinimumNumberOfIngredientsRequired.ForRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient entry for 0} not found in recipe {1}..
        /// </summary>
        internal static string Recipes_RecipeIngredientEntryNotFound {
            get {
                return ResourceManager.GetString("Recipes.RecipeIngredientEntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient {0} not found in recipe {1}..
        /// </summary>
        internal static string Recipes_RecipeIngredientNotFound {
            get {
                return ResourceManager.GetString("Recipes.RecipeIngredientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe {0} not found.
        /// </summary>
        internal static string Recipes_RecipeNotFound {
            get {
                return ResourceManager.GetString("Recipes.RecipeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipe type must be selected..
        /// </summary>
        internal static string Recipes_RecipeTypeMustBeSelected {
            get {
                return ResourceManager.GetString("Recipes.RecipeTypeMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be positive.
        /// </summary>
        internal static string RecipeValueObjectsErrors_IngredientAmountNotPositive {
            get {
                return ResourceManager.GetString("RecipeValueObjectsErrors.IngredientAmountNotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration must be positive.
        /// </summary>
        internal static string RecipeValueObjectsErrors_RecipeDurationNotPositive {
            get {
                return ResourceManager.GetString("RecipeValueObjectsErrors.RecipeDurationNotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe name must be at least 3 characters..
        /// </summary>
        internal static string RecipeValueObjectsErrors_RecipeNameTooShort {
            get {
                return ResourceManager.GetString("RecipeValueObjectsErrors.RecipeNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image URL extension : {0}.
        /// </summary>
        internal static string SharedErrors_InvalidImageUrlExtensionError {
            get {
                return ResourceManager.GetString("SharedErrors.InvalidImageUrlExtensionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image URL format : {0}.
        /// </summary>
        internal static string SharedErrors_InvalidImageUrlFormatError {
            get {
                return ResourceManager.GetString("SharedErrors.InvalidImageUrlFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image URL cannot be null.
        /// </summary>
        internal static string SharedErrors_NullImageUrlError {
            get {
                return ResourceManager.GetString("SharedErrors.NullImageUrlError", resourceCulture);
            }
        }
    }
}
