namespace CookBook.CleanArch.Infrastructure.Migrator.SeedData;

internal static class IngredientSeedData
{
    public static IReadOnlyList<IngredientSeedItem> Items =>
    [
        new IngredientSeedItem(name: "Sugar", description: "fine white sugar commonly used as a sweetener", imageUrl: "https://images.unsplash.com/photo-1709651808265-977ed7ef78c6?q=80&w=1738&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Mint", description: "fresh aromatic green leaves", imageUrl: null),
        new IngredientSeedItem(name: "Lime", description: null, imageUrl: "https://images.unsplash.com/photo-1648437595604-f1794490053c?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Lemon", description: "sour yellow citrus fruit", imageUrl: "https://i.imgur.com/YYPzexp.png"),
        new IngredientSeedItem(name: "Soda", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Rum", description: "distilled alcoholic beverage from sugarcane", imageUrl: null),
        new IngredientSeedItem(name: "Vodka", description: null, imageUrl: "https://images.unsplash.com/photo-1595430712287-744ad635e266?q=80&w=1354&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Orange Juice", description: "freshly squeezed orange juice", imageUrl: "https://images.unsplash.com/photo-1613478223719-2ab802602423?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Ice", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Coffee", description: "strong brewed black coffee", imageUrl: null),
        new IngredientSeedItem(name: "Milk", description: null, imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Chocolate", description: "sweet cocoa-based ingredient", imageUrl: "https://images.unsplash.com/photo-1626697556651-67ebdcb8cbd6?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Banana", description: "soft tropical fruit", imageUrl: null),
        new IngredientSeedItem(name: "Strawberry", description: null, imageUrl: "https://images.unsplash.com/photo-1722803672529-5a7a85728479?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Water", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Vanilla Syrup", description: "sweet vanilla flavored syrup", imageUrl: "https://images.unsplash.com/photo-1770376924086-5c9f36723081?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Caramel Syrup", description: "rich caramel coffee syrup", imageUrl: "https://images.unsplash.com/photo-1568657704598-602700bd9694?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Cinnamon", description: null, imageUrl: "https://images.unsplash.com/photo-1553499944-e4297a0af1bd?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Honey", description: null, imageUrl: "https://images.unsplash.com/photo-1613548058193-1cd24c1bebcf?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Green Tea", description: "ground green tea or brewed concentrate", imageUrl: "https://images.unsplash.com/photo-1546662661-de70c19756be?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Black Tea", description: null, imageUrl: "https://images.unsplash.com/photo-1627828094454-accc9a7c20e9?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Ginger", description: "fresh aromatic ginger root", imageUrl: "https://images.unsplash.com/photo-1635843104103-ddd88e1c5141?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Apple Juice", description: null, imageUrl: "https://images.unsplash.com/photo-1590240568206-4e97becae4ef?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Pineapple Juice", description: null, imageUrl: "https://images.unsplash.com/photo-1636386794950-aae736311f41?q=80&w=1163&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Cranberry Juice", description: null, imageUrl: "https://images.unsplash.com/photo-1670398563365-156dcbad9b9b?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Tonic Water", description: null, imageUrl: "https://images.unsplash.com/photo-1652256071713-ffc3d9f6bdf3?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Gin", description: null, imageUrl: "https://images.unsplash.com/photo-1700485869901-d22cf64c4d7d?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Tequila", description: null, imageUrl: "https://images.unsplash.com/photo-1529671434436-8fbb37410056?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Triple Sec", description: null, imageUrl: "https://images.unsplash.com/photo-1774537642349-f84ae0f4e2f8?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
        new IngredientSeedItem(name: "Whiskey", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Red Wine", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Beer", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Butter", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Flour", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Egg", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Baking Powder", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Vanilla Extract", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Cream Cheese", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Mascarpone", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Ladyfingers", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Espresso Shot", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Cocoa Powder", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Whipped Cream", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Oats", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Yogurt", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Blueberries", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Raspberries", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Coconut Milk", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Orange Liqueur", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Soda Water", description: null, imageUrl: null),
        new IngredientSeedItem(name: "Tatratea 22%", description: null, imageUrl: "https://tatrateashop.sk/wp-content/uploads/2024/05/tatratea_22_coconut.png"),
        new IngredientSeedItem(name: "Tatratea 32%", description: null, imageUrl: "https://tatrateashop.sk/wp-content/uploads/2024/05/tatratea_32_citrus.png"),
        new IngredientSeedItem(name: "Tatratea 42%", description: null, imageUrl: "https://tatrateashop.sk/wp-content/uploads/2024/05/tatratea_42_peach.png"),
        new IngredientSeedItem(name: "Tatratea 52%", description: null, imageUrl: "https://tatrateashop.sk/wp-content/uploads/2024/05/tatratea_52_original.png"),
        new IngredientSeedItem(name: "Tatratea 62%", description: null, imageUrl: "https://tatrateashop.sk/wp-content/uploads/2024/05/tatratea_62_forest_fruit.png"),
        new IngredientSeedItem(name: "Tatratea 72%", description: null, imageUrl: "https://tatrateashop.sk/wp-content/uploads/2024/05/tatratea_72_outlaw.png"),
    ];
}

internal sealed record IngredientSeedItem(string name, string? description, string? imageUrl);
